METHOD: poco
POCO:
  ACTIVATION_TYPE: sigmoid
  BACKBONE: hrnet_w32-pare
  BETA_LOSS_WEIGHT: 0.001
  BETA_UNCERT_WEIGHT: 1.0
  COND_NFLOW: true
  CONTEXT_DIM: 512
  EXCLUDE_UNCERT_IDX: ''
  GENG_LOSS_WEIGHT: 1.0
  GT_TRAIN_WEIGHT: 1.0
  JNT_UNCERT_WEIGHT: 1.0
  KEYPOINT_2D_LOSS_WEIGHT: 2.5
  KEYPOINT_3D_LOSS_WEIGHT: 5.0
  KINEMATIC_UNCERT: false
  LOG_TRAIN_UNCERT: 100
  LOG_UNCERT_STAT: 5
  LOSS_VER: norm_flow_res_gaus
  LOSS_WEIGHT: 60.0
  MASK_PARAMS_ID: ''
  NFLOW_MASK_TYPE: alter
  NF_LOSS_WEIGHT: 0.0001
  NUM_FLOW_LAYERS: 3
  NUM_NEURONS: 512-
  NUM_NF_RV: 9
  OPENPOSE_TRAIN_WEIGHT: 0.0
  POSE_LOSS_WEIGHT: 1.0
  POSE_UNCERT_WEIGHT: 0.01
  SIGMA_DIM: 1
  SMPL_RENDER_LOSS_WEIGHT: 1.0
  SMPL_SEGM_LOSS_WEIGHT: 1.0
  UNCERT_INP_TYPE: feat-pose
  UNCERT_LAYER: diff_branch
  UNCERT_STATS_FILE: ''
  UNCERT_TYPE: pose
  USE_DROPOUT: true
  USE_ITER_FEATS: true
  USE_KEYCONF: false
PREF_LOGGER: tensorboard
RUN_TEST: false
SEED_VALUE: 88